export interface MenuItem {
  name: string;
  price: number;
  desc?: string;
  isSpicy?: boolean;
  isPopular?: boolean;
  isChefSpecial?: boolean;
}

export interface MenuCategory {
  id: string;
  title: string;
  hindiTitle?: string;
  count: number;
  icon: string;
  items: MenuItem[];
}

export const COMPLETE_MENU: MenuCategory[] = [
  {
    id: "soups",
    title: "Soups",
    hindiTitle: "सूप",
    count: 5,
    icon: "🍲",
    items: [
      { name: "Hot and Sour Soup", price: 150, isSpicy: true },
      { name: "Sweet Corn Soup", price: 150 },
      { name: "Manchow Soup", price: 150, isPopular: true },
      { name: "Cream of Tomato Basil Soup", price: 150 },
      { name: "Lemon Coriander Soup", price: 150 },
    ],
  },
  {
    id: "starters",
    title: "Starters & Small Plates",
    hindiTitle: "स्टार्टर्स",
    count: 22,
    icon: "🍢",
    items: [
      { name: "Popcorn", price: 204 },
      { name: "French Fries", price: 240 },
      { name: "Peri Peri Fries", price: 240, isSpicy: true },
      { name: "Italian Baked Kulcha", price: 303, isChefSpecial: true },
      { name: "Tandoori Cheese Baked Kulcha", price: 303, isPopular: true },
      { name: "Punjabi Baked Kulcha", price: 303 },
      { name: "Paneer Tikka", price: 303, isPopular: true },
      { name: "Hara Bhara Kebab", price: 303 },
      { name: "Dahi Kebab", price: 303, isChefSpecial: true },
      { name: "Amritsari Chaap", price: 303, isSpicy: true },
      { name: "Malai Soya Chaap", price: 303, isPopular: true },
      { name: "Chilli Paneer Dry", price: 303, isSpicy: true },
      { name: "Chinese Bhel", price: 303 },
      { name: "Cheese Garlic Bread", price: 303 },
      { name: "Cheese Garlic Toast", price: 303 },
      { name: "Chilli Mushroom Dry", price: 303 },
      { name: "Manchurian Dry", price: 303 },
      { name: "Baby Corn", price: 303 },
      { name: "Cheese Balls", price: 303 },
      { name: "Cheese Kulcha Bomb", price: 402, isChefSpecial: true, isPopular: true },
      { name: "Amritsari Kulcha Bomb", price: 402, isChefSpecial: true },
      { name: "Tomato Basil Bruschetta", price: 402 },
    ],
  },
  {
    id: "momo",
    title: "Momo Corner",
    hindiTitle: "मोमो",
    count: 3,
    icon: "🥟",
    items: [
      { name: "Veg Steam Momo", price: 150 },
      { name: "Punjabi Tandoori Momo", price: 240, isPopular: true, isSpicy: true },
      { name: "Pan Fried Veg Momo", price: 240 },
    ],
  },
  {
    id: "maggie",
    title: "Maggie Specials",
    hindiTitle: "मैगी",
    count: 3,
    icon: "🍜",
    items: [
      { name: "Masala Maggie", price: 150 },
      { name: "Veg Maggie", price: 240 },
      { name: "Cheese Maggie", price: 240, isPopular: true },
    ],
  },
  {
    id: "italian",
    title: "Italian Pasta & Bakes",
    hindiTitle: "इटैलियन",
    count: 4,
    icon: "🍝",
    items: [
      { name: "Mix Sauce Pasta", price: 402, isPopular: true },
      { name: "Lasagne", price: 402, isChefSpecial: true },
      { name: "Veg au Gratin", price: 402 },
      { name: "Alfredo Pasta", price: 402 },
    ],
  },
  {
    id: "tandoori-bread",
    title: "Tandoori Breads & Signature Kulchas",
    hindiTitle: "तंदूरी ब्रेड व कुल्चे",
    count: 19,
    icon: "🫓",
    items: [
      { name: "Tawa Roti (Fulka)", price: 24 },
      { name: "Tandoori Roti", price: 42 },
      { name: "Butter Tandoori Roti", price: 51 },
      { name: "Plain Naan", price: 51 },
      { name: "Rumali Roti", price: 51 },
      { name: "Adrak Mirchi Ki Roti", price: 60, isSpicy: true },
      { name: "Butter Naan", price: 60, isPopular: true },
      { name: "Makki Ki Roti (Seasonal)", price: 60 },
      { name: "Missi Roti", price: 60 },
      { name: "Garlic Naan", price: 105, isPopular: true },
      { name: "Cheese Garlic Naan", price: 123, isPopular: true },
      { name: "Olive Parmesan Naan", price: 123, isChefSpecial: true },
      { name: "Amritsari Kulcha", price: 132, isPopular: true, isChefSpecial: true },
      { name: "Cheese Chilli Kulcha", price: 132, isSpicy: true },
      { name: "Mix Stuffed Kulcha", price: 132 },
      { name: "Onion Garlic Kulcha", price: 132 },
      { name: "Special Kulcha", price: 150 },
      { name: "King of Cheese Naan", price: 303, isChefSpecial: true },
      { name: "King of Kulcha", price: 402, isChefSpecial: true, isPopular: true },
    ],
  },
  {
    id: "indian-mains",
    title: "Indian Main Course",
    hindiTitle: "मेन कोर्स",
    count: 29,
    icon: "🥘",
    items: [
      { name: "Aloo Dum Masaladar", price: 303 },
      { name: "Aloo Do Pyaza", price: 303 },
      { name: "Amritsari Chole Masala", price: 303, isPopular: true },
      { name: "Mix Veg Jalfrezi", price: 303 },
      { name: "Yellow Dal Tadka", price: 303 },
      { name: "Paneer Makhani Wala", price: 303, isPopular: true },
      { name: "Methi Matar Malai", price: 303 },
      { name: "Dal Makhani", price: 303, isPopular: true, isChefSpecial: true },
      { name: "Paneer Butter Masala", price: 330, isPopular: true },
      { name: "Kadhai Paneer", price: 330, isSpicy: true },
      { name: "Paneer Tikka Masala", price: 330, isPopular: true },
      { name: "Paneer Do Pyaza", price: 330 },
      { name: "Mushroom Masala / Mushroom Jalfrezi", price: 330 },
      { name: "Green Peas Mushroom", price: 330 },
      { name: "Veg Kofta", price: 303 },
      { name: "Mushroom Masala Gravy", price: 303 },
      { name: "Kadhai Soya Chaap", price: 303, isSpicy: true },
      { name: "Lehsuni Soya Chaap", price: 303 },
      { name: "Malai Soya Chaap", price: 303, isPopular: true },
      { name: "Sarson Ki Saag (Seasonal)", price: 303 },
      { name: "Palak Paneer", price: 303 },
      { name: "Corn Palak", price: 303 },
      { name: "Paneer Makhani", price: 330 },
      { name: "Lachuni Paneer Masala", price: 330 },
      { name: "Matar Paneer", price: 330 },
      { name: "Malai Kofta", price: 330, isChefSpecial: true, isPopular: true },
      { name: "Paneer Chatpata", price: 330, isSpicy: true },
      { name: "Tandoori Matka Dal", price: 402, isChefSpecial: true },
    ],
  },
  {
    id: "rice-biryani",
    title: "Rice & Biryani",
    hindiTitle: "चावल व बिरयानी",
    count: 6,
    icon: "🍚",
    items: [
      { name: "Steamed Rice", price: 240 },
      { name: "Jeera Rice", price: 303 },
      { name: "Veg Pulao", price: 303 },
      { name: "Veg Dum Biryani", price: 303, isPopular: true },
      { name: "Soya Chaap Biryani", price: 303, isPopular: true },
      { name: "Paneer Tikka Biryani", price: 303, isChefSpecial: true },
    ],
  },
  {
    id: "extras",
    title: "Accompaniments & Extras",
    hindiTitle: "एक्स्ट्रा",
    count: 7,
    icon: "🥗",
    items: [
      { name: "Roasted Papad", price: 51 },
      { name: "Extra Cheese", price: 60 },
      { name: "Masala Papad", price: 81 },
      { name: "Onion Salad", price: 105 },
      { name: "Green Salad", price: 150 },
      { name: "Boondi Raita", price: 150 },
      { name: "Mix Veg Raita", price: 150 },
    ],
  },
  {
    id: "chinese-rice-noodles",
    title: "Chinese Rice & Noodles",
    hindiTitle: "चाइनीज",
    count: 10,
    icon: "🥡",
    items: [
      { name: "Chilli Garlic Noodles", price: 303, isSpicy: true },
      { name: "Chilli Garlic Rice", price: 303, isSpicy: true },
      { name: "Mongolian Noodles", price: 303 },
      { name: "Mongolian Rice", price: 303 },
      { name: "Paneer Fried Rice", price: 303, isPopular: true },
      { name: "Paneer Noodles", price: 303 },
      { name: "Schezwan Fried Rice", price: 303, isSpicy: true },
      { name: "Veg Fried Rice", price: 303 },
      { name: "Veg Hakka Noodles", price: 303, isPopular: true },
      { name: "Mexican Rice", price: 303 },
    ],
  },
  {
    id: "desserts",
    title: "Desserts & Sweet Tooth",
    hindiTitle: "मीठा",
    count: 6,
    icon: "🍨",
    items: [
      { name: "Hot Gulab Jamun", price: 60 },
      { name: "Hot Brownie", price: 105 },
      { name: "Hot Gulab Jamun with Ice Cream", price: 132, isPopular: true },
      { name: "Vanilla Ice Cream", price: 150 },
      { name: "Bombay Kulfi", price: 204, isChefSpecial: true },
      { name: "Sizzling Brownie with Ice Cream", price: 204, isPopular: true, isChefSpecial: true },
    ],
  },
  {
    id: "pizza",
    title: "Artisan Pizza",
    hindiTitle: "पिज़्ज़ा",
    count: 3,
    icon: "🍕",
    items: [
      { name: "Six Cheese Pizza", price: 402, isChefSpecial: true, isPopular: true },
      { name: "Margherita Pizza", price: 402 },
      { name: "Six Topping Pizza", price: 402 },
    ],
  },
  {
    id: "beverages",
    title: "Beverages, Shakes & Coolers",
    hindiTitle: "पेय",
    count: 16,
    icon: "🍹",
    items: [
      { name: "Mineral Water", price: 33 },
      { name: "Chai (Masala/Kesariya)", price: 60 },
      { name: "Black Tea", price: 60 },
      { name: "Cold Coffee", price: 105, isPopular: true },
      { name: "Cold Drink (Can)", price: 105 },
      { name: "Hot Coffee", price: 123 },
      { name: "Mint Mojito", price: 150, isPopular: true },
      { name: "Masala Thums Up", price: 150 },
      { name: "Virgin Mojito", price: 150 },
      { name: "Fresh Lime Soda", price: 150 },
      { name: "Cold Coffee with Ice Cream", price: 222, isPopular: true },
      { name: "Strawberry Shake", price: 222 },
      { name: "Brownie Shake", price: 222, isChefSpecial: true },
      { name: "Oreo Shake", price: 222 },
      { name: "KitKat Shake", price: 222 },
      { name: "Red Bull", price: 222 },
    ],
  },
  {
    id: "sizzlers",
    title: "Sizzlers",
    hindiTitle: "सिज़लर",
    count: 3,
    icon: "♨️",
    items: [
      { name: "Chinese Sizzler", price: 402 },
      { name: "Mexican Sizzler", price: 402 },
      { name: "Italian Sizzler", price: 402, isChefSpecial: true },
    ],
  },
  {
    id: "rolls",
    title: "Kathi Rolls",
    hindiTitle: "काठी रोल",
    count: 4,
    icon: "🌯",
    items: [
      { name: "Malai Chaap Kathi Roll", price: 150, isPopular: true },
      { name: "Paneer Tikka Masala Kathi Roll", price: 150 },
      { name: "Soya Chaap Kathi Roll", price: 150 },
      { name: "Tandoori Veggie Cheese Kathi Roll", price: 150, isChefSpecial: true },
    ],
  },
  {
    id: "indian-combo",
    title: "Indian Combos",
    hindiTitle: "इंडियन कॉम्बो",
    count: 4,
    icon: "🍱",
    items: [
      { name: "Amritsari Kulcha with Chole", price: 303, isPopular: true },
      { name: "Onion Garlic Kulcha with Paneer Tikka Masala", price: 303 },
      { name: "Mix Stuffed Kulcha with Paneer Butter Masala", price: 303 },
      { name: "Cheese Kulcha with Paneer Tikka Masala", price: 303, isChefSpecial: true },
    ],
  },
  {
    id: "indian-special-combo",
    title: "Indian Special Grand Combos",
    hindiTitle: "ग्रैंड कॉम्बो",
    count: 3,
    icon: "👑",
    items: [
      { name: "Kadai Paneer + Dal Makhani + Masala Kulcha + Veg Pulao + Raita + Papad", price: 402, isPopular: true },
      { name: "Amritsari Chole + Dal Makhani + Amritsari Kulcha + Jeera Rice + Raita + Papad", price: 402, isChefSpecial: true },
      { name: "Dal Makhani + Paneer Butter Masala + Masala Kulcha + Biryani + Raita + Papad", price: 402, isChefSpecial: true },
    ],
  },
  {
    id: "indian-thali",
    title: "Indian Thali",
    hindiTitle: "थाली",
    count: 1,
    icon: "🍽️",
    items: [
      { name: "Indian Thali (Only for Parcel)", price: 240, isPopular: true },
    ],
  },
  {
    id: "chinese-combo",
    title: "Chinese Combos",
    hindiTitle: "चाइनीज कॉम्बो",
    count: 4,
    icon: "🥢",
    items: [
      { name: "Veg Hakka Noodles & Chilli Paneer", price: 303, isPopular: true },
      { name: "Veg Fried Rice & Veg Manchurian", price: 303 },
      { name: "Veg Hakka Noodles & Veg Manchurian Gravy", price: 303 },
      { name: "Chilli Mushroom Gravy & Chilli Garlic Noodles", price: 303 },
    ],
  },
  {
    id: "hookah-flavours",
    title: "Flavoured Mouth Fresheners & Premium Hookah Flavours",
    hindiTitle: "हुक्का फ्लेवर्स",
    count: 8,
    icon: "🍃",
    items: [
      { name: "Commissioner", price: 600 },
      { name: "Gum Supari", price: 600 },
      { name: "Paan Masti Gum", price: 600, isPopular: true },
      { name: "Commissioner Gum", price: 600 },
      { name: "Blue Berry Spring Water", price: 600, isChefSpecial: true },
      { name: "Mix Fruit", price: 600 },
      { name: "Teen Paan Rose", price: 600, isPopular: true },
      { name: "Lemon Rasna", price: 600 },
    ],
  },
  {
    id: "hookah-collection",
    title: "Premium Hookah Collection",
    hindiTitle: "प्रीमियम हुक्का",
    count: 4,
    icon: "💨",
    items: [
      { name: "Matka Hookah", price: 900, isPopular: true },
      { name: "Vodka Bottle Hookah", price: 900, isChefSpecial: true },
      { name: "Astronaut Hookah", price: 900 },
      { name: "Dubai Special Hookah", price: 900, isPopular: true },
    ],
  },
  {
    id: "tower-hookah",
    title: "TIKH Special Tower Hookah",
    hindiTitle: "टावर हुक्का",
    count: 1,
    icon: "🗼",
    items: [
      { name: "Tower Hookah", price: 1500, isChefSpecial: true, isPopular: true },
    ],
  },
  {
    id: "hookah-bases",
    title: "Hookah Base Options & Add-ons",
    hindiTitle: "हुक्का बेस",
    count: 4,
    icon: "🧊",
    items: [
      { name: "Ice Base", price: 60 },
      { name: "Milk Base", price: 60 },
      { name: "Coal Change", price: 60 },
      { name: "Red Bull Base", price: 222, isPopular: true },
    ],
  },
];
